@boundary={{boundary}}

# @baseAddress=https://api.openai.com/v1

# @baseAddress=https://localhost:7000/openai/v1

@baseAddress={{openai_api_reverse_proxy}}/v1

### baidu
GET https://www.baidu.com


### upload file for fine-tunes
POST {{baseAddress}}/files
Authorization: Bearer {{openai_token}}
Content-Type: multipart/form-data; boundary="{{boundary}}"

--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=purpose

fine-tune
--{{boundary}}
Content-Disposition: form-data; name=file; filename=data_prepared.jsonl;

< Assets\fine-tunes.data_prepared.jsonl
--{{boundary}}--


### fine-tunes
GET {{baseAddress}}/fine-tunes HTTP/1.1
Authorization: Bearer {{openai_token}}


### embeddings
POST {{baseAddress}}/embeddings HTTP/1.1
content-type: application/json
Authorization: Bearer {{openai_token}}

{
  "model": "text-embedding-ada-002",
  "input": 
    "The food was delicious and the waiter...1"
}


### Create image OK
POST {{baseAddress}}/images/generations HTTP/1.1
content-type: application/json
Authorization: Bearer {{openai_token}}

{
  "prompt": "A beautiful girl with a full beard on her face",
  "n": 2,
  "size": "1024x1024"
}

### Create image edit (upload) OK
POST {{baseAddress}}/images/edits
Authorization: Bearer {{openai_token}}
Content-Type: multipart/form-data; boundary="{{boundary}}"

--{{boundary}}
Content-Disposition: form-data; name=image; filename=image_edit_original.png; filename*=utf-8''image_edit_original.png
Content-Type: image/png

< Assets\a.png
--{{boundary}}
Content-Disposition: form-data; name=mask; filename=image_edit_mask.png; filename*=utf-8''image_edit_mask.png
Content-Type: image/png

< Assets\a.mask.png
--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=prompt

A sunlit indoor lounge area with a pool containing a big pig
--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=n

2
--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=size

1024x1024
--{{boundary}}--


### Create image variation 创建图像变体 OK
POST {{baseAddress}}/images/variations
Authorization: Bearer {{openai_token}}
Content-Type: multipart/form-data; boundary="{{boundary}}"

--{{boundary}}
Content-Disposition: form-data; name=image; filename=image_edit_original.png; filename*=utf-8''image_edit_original.png
Content-Type: image/png

< Assets\a.png
--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=n

2
--{{boundary}}
Content-Type: text/plain;
Content-Disposition: form-data; name=size

1024x1024
--{{boundary}}--